import type {
  Cliente,
  DocumentoAiResultado,
  ExpedienteNegocio,
  Prospecto,
} from '@ylika/shared';

export const prospectosSeed: Prospecto[] = [
  {
    id: 'pro-1',
    codigo: 'PRO-00124',
    nombre: 'Expansión Planta Sur',
    empresa: 'CEMEX México',
    etapa: 'propuesta',
    valorEstimado: 890000,
    probabilidad: 65,
    ejecutivo: 'Ana Ruiz',
    ultimoContacto: '2026-03-12',
    origen: 'Referido',
  },
  {
    id: 'pro-2',
    codigo: 'PRO-00131',
    nombre: 'Modernización Línea 3',
    empresa: 'Grupo Bimbo',
    etapa: 'negociacion',
    valorEstimado: 1200000,
    probabilidad: 78,
    ejecutivo: 'Carlos Méndez',
    ultimoContacto: '2026-03-13',
    origen: 'Inbound',
  },
];

export const clientesSeed: Cliente[] = [
  {
    id: 'cli-1',
    codigo: 'CLI-00088',
    nombre: 'SHAMOSH',
    rfc: 'SHA850101AB1',
    industria: 'Construcción',
    sector: 'privado',
    ejecutivo: 'Ana Ruiz',
    expedientesActivos: 2,
    valorCartera: 150000,
    creditoDisponible: 350000,
    estado: 'activo',
  },
  {
    id: 'cli-2',
    codigo: 'CLI-00091',
    nombre: 'Planta Norte Industrial',
    rfc: 'PNI920315XY9',
    industria: 'Manufactura',
    sector: 'gobierno',
    ejecutivo: 'Carlos Méndez',
    expedientesActivos: 1,
    valorCartera: 12000000,
    creditoDisponible: 8000000,
    estado: 'activo',
  },
];

export const expedientesSeed: ExpedienteNegocio[] = [
  {
    id: 'exp-1',
    codigo: 'EXP-000452',
    nombre: 'Venta Directa SHAMOSH',
    clienteId: 'cli-1',
    clienteNombre: 'SHAMOSH',
    tipo: 'venta_directa',
    sector: 'privado',
    valor: 150000,
    estado: 'cobranza',
    avance: 82,
    rentabilidad: 28,
    ejecutivo: 'Ana Ruiz',
    empresa: 'YLIKA Operaciones',
    actualizadoEn: '2026-03-14T09:20:00Z',
    resumen: {
      montoVendido: 150000,
      montoComprado: 78000,
      facturadoCliente: 150000,
      cobradoCliente: 90000,
      facturadoProveedor: 78000,
      pagadoProveedor: 45000,
      utilidadBruta: 72000,
      utilidadNeta: 42000,
      margen: 28,
      roi: 34,
    },
    timeline: [
      {
        id: 't1',
        label: 'Cotización',
        sublabel: 'Aprobada',
        estado: 'completado',
        fecha: '2026-01-12',
        monto: 150000,
      },
      {
        id: 't2',
        label: 'Pedido',
        estado: 'completado',
        fecha: '2026-01-18',
        monto: 150000,
      },
      {
        id: 't3',
        label: 'Remisión',
        estado: 'completado',
        fecha: '2026-02-02',
      },
      {
        id: 't4',
        label: 'Factura',
        estado: 'completado',
        fecha: '2026-02-05',
        monto: 150000,
      },
      {
        id: 't5',
        label: 'Cobro',
        sublabel: 'Parcial $90,000',
        estado: 'activo',
        fecha: '2026-03-01',
        monto: 90000,
      },
    ],
    graph: { nodes: [], edges: [] },
    insights: [
      {
        id: 'i1',
        severidad: 'warning',
        titulo: 'Cobranza parcial',
        descripcion: 'Quedan $60,000 pendientes de cobro en FAC-00452.',
        impacto: 'Flujo de caja del expediente debajo del plan.',
        recomendacion: 'Programar seguimiento de cobranza esta semana.',
        entidadRelacionada: 'FAC-00452',
      },
    ],
  },
  {
    id: 'exp-2',
    codigo: 'EXP-000875',
    nombre: 'PLANTA NORTE',
    clienteId: 'cli-2',
    clienteNombre: 'Planta Norte Industrial',
    tipo: 'proyecto',
    sector: 'gobierno',
    valor: 12000000,
    estado: 'ejecucion',
    avance: 68,
    rentabilidad: 24,
    ejecutivo: 'Carlos Méndez',
    empresa: 'YLIKA Operaciones',
    actualizadoEn: '2026-03-14T11:05:00Z',
    resumen: {
      montoVendido: 12000000,
      montoComprado: 2100000,
      facturadoCliente: 4500000,
      cobradoCliente: 4500000,
      facturadoProveedor: 2100000,
      pagadoProveedor: 1300000,
      utilidadBruta: 9900000,
      utilidadNeta: 2880000,
      margen: 24,
      roi: 31,
    },
    timeline: [
      {
        id: 't1',
        label: 'Cotización Aprobada',
        estado: 'completado',
        monto: 12000000,
      },
      { id: 't2', label: 'Contrato Firmado', estado: 'completado' },
      { id: 't3', label: 'Proyecto Iniciado', estado: 'completado' },
      {
        id: 't4',
        label: 'OC-001',
        sublabel: '$2,100,000',
        estado: 'activo',
        monto: 2100000,
      },
      { id: 't5', label: 'Orden', estado: 'pendiente' },
      { id: 't6', label: 'Procesos', estado: 'pendiente' },
      { id: 't7', label: 'Resultado', estado: 'pendiente' },
    ],
    graph: { nodes: [], edges: [] },
    insights: [
      {
        id: 'i1',
        severidad: 'critical',
        titulo: 'Riesgo detectado',
        descripcion: 'OC-002 no tiene factura proveedor.',
        impacto: 'Riesgo de retraso en entrega.',
        recomendacion: 'Solicitar CFDI al proveedor.',
        entidadRelacionada: 'OC-002',
      },
    ],
  },
];

export const documentoAiSeed: DocumentoAiResultado = {
  archivo: 'cotizacion_cemex.pdf',
  clasificacion: 'Cotización de proveedor',
  proveedor: 'CEMEX',
  monto: 450000,
  concepto: 'Concreto',
  proyecto: 'Planta Norte',
  resumen: 'Cotización de concreto CEMEX para Planta Norte.',
  provider: 'heuristic',
  confianzaExtraccion: 0.7,
  expedienteSugerido: {
    codigo: 'EXP-000875',
    nombre: 'Planta Norte',
    confianza: 0.92,
  },
  duplicados: [],
  campos: {
    Proveedor: 'CEMEX',
    Monto: 450000,
    Concepto: 'Concreto',
    Proyecto: 'Planta Norte',
  },
};
